### PR TITLE
Export the function for rendering the default items

### PR DESCRIPTION
**Pull request by agentS**
Export the function for rendering the default representation of the items.

### CODE REVIEW

**Comment by iannbing** [comment]
Please branch out from `development` for your PR. The only branch that can be merged to master is `development`.

**Comment by iannbing** [comment]
@agentS I created a slightly-bigger PR that includes your proposed change. Please see #82 .

**Comment by agentS** [comment]
Great, thank you so much! Is there any way I can buy you a coffee or make a small donation?

**Comment by iannbing** [comment]
Wow, thanks! You can buy me a coffee via [paypal](https://paypal.me/iannbing).
I've released version `1.1.4`. To extend the default UI, please check README examples.

**Pull request closed without merging**
